name: Release
on:
  push:
    branches: ["main"]
jobs:
  playbook:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: read
      statuses: write
    name: Run playbook
    steps:
      - uses: actions/checkout@v4
      - name: Get Pull Request Number
        id: pr
        run: |
            echo "pull_request_number=$(gh pr list --limit 1 --state merged --base main)" >> $GITHUB_ENV
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo PR number
        run: echo "pr number is ${{ env.pull_request_number}}"