name: release
on:
  push:
    branches: ["main"]
jobs:
  playbook:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: read
      statuses: write
    name: Run playbook
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: echo test action1 trigger action2

